### ISSUE TITLE
Italics still wont work in Intelli J and causes the Garbled Content

### ISSUE THREAD

**Issue by vikky49** [adobe-fonts/source-code-pro#108]
A bug was opened against the Intelli J folks to see if  this is some thing that needs to be fixed on their Side ..

This was the response from them ..
"
PostScript font name for the font can be checked e.g. in Font Book application. Font will be recognized as an italic one if the name contains 'italic', 'cursiva', 'oblique' or 'inclined' in it.
For Source Code Pro Italic, PostScript name is SourceCodePro-It, so, unfortunately, the detection doesn't work.

I'll reopen this issue, to track the problem for such fonts, but it's unlikely to be fixed soon, as a change to JDK will most probably be required. "

So the question is ..Is it some thing that can be fixed on the Font names side ..

For further reference here is the YouTrack Ticket.

https://youtrack.jetbrains.com/issue/IDEA-90072

**Comment by miguelsousa** [comment]
> Is it some thing that can be fixed on the Font names side

We can't change the PostScript names used by the Source Code fonts because that would break existing documents and create conflicts with the older version of the fonts.

And based on [this comment](https://youtrack.jetbrains.com/issue/IDEA-90072#comment=27-1110637) by Karl Shea about *Office Code Pro*, it sounds like modifying the fonts' PS names won't solve the Intelli J issue.

Using heuristics on the PS name is a really poor way of determining if a font is italic. What Intelli J should be doing is checking the fonts' [`fsSelection`](https://www.microsoft.com/typography/otspec/os2.htm#fss) bit.
