### ISSUE TITLE
Underline Appears as 'i' in Italic in IntelliJ 

### ISSUE THREAD

**Issue by hf** [adobe-fonts/source-code-pro#111]
I just installed the latest release (https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro%2F1.030R-it) and applied the font to my IntelliJ / Android Studio setup.

This is what I get on italics with underlines: 
![Font Issue](https://cloud.githubusercontent.com/assets/295870/10724628/51a863e2-7bc6-11e5-83b1-342d7cd88d76.png)

**Comment by codeman38** [comment]
To help troubleshoot, what operating system are you using, and which format of the font (.ttf or .otf) did you install?

**Comment by hf** [comment]
Windows 7 Enterprise. Firstly I tried OTF, then TTF. Same result.

**Comment by manuel-uberti** [comment]
Don't know if this can help, but I'm using latest Source Code Pro on Debian Sid and Emacs and everything works as expected.

**Comment by TigerC10** [comment]
I use the entire suite of JetBrains IDEs, and I've tried to replicate the issue on each of them with TTF - no dice.  Of course, I'm using Mac OSX and not Windows, but since it's a Java based IDE that _shouldn't_ matter.

IntelliJ based IDEs have always had some trouble with custom fonts - particularly with non-monospace fonts.  I remember using Source Code Pro with IntelliJ and occasionally my entire file became garbage chars.  This happened back when IntelliJ didn't pick up Source Code Pro as a monospaced font, but since Source Code Pro updated and fixed the monospace flag, it hasn't happened.  Even when it did happen, restarting the IDE has always fixed it.

I suspect this is a problem with how IntelliJ handles the custom font selection.  Probably an issue for JetBrains to look at, not Adobe.

**Comment by codeman38** [comment]
I can't reproduce this in Windows 7 either. Possibly an issue with the Windows font cache?

**Comment by miguelsousa** [comment]
That's my guess as well, font cache issue.

**Comment by hf** [comment]
I deleted FNTCACHE.DAT, no luck.

**Comment by hf** [comment]
There is also this: 
![issue](https://cloud.githubusercontent.com/assets/295870/10783139/cc142dd8-7d55-11e5-930f-d452a82aa1e8.png)

**Comment by miguelsousa** [comment]
The only strings affected by this problem are the slanted ones, it seems.
Also, it seems to me that that's not the italic font, but instead a slanted upright font.
Are you sure that the italic fonts are properly installed?

**Comment by codeman38** [comment]
I assume you've already tried rebooting Windows since installing the fonts? If not, it's worth a try. If so...try deleting them, rebooting, and then reinstalling them, possibly?

**Comment by joaoevangelista** [comment]
It's worth too, after deleting all fonts and rebooting, clear and invalidate the IntelliJ cache, you can find this option under File menu at editor, then install only TTF, OTF  is buggy with Java
