### ISSUE TITLE
Create a more condensed version of the font

### ISSUE THREAD

**Issue by digulla** [adobe-fonts/source-code-pro#12]
The current version of the font looks wider than tall. While this helps with readability, it's about 20% wider than the default Ubuntu Monospace font.

I'd like a font version which uses horizontal space more conservatively.

**Comment by alex-ball** [comment]
The use case for a more condensed version is not so much when the font is being used in isolation, but when it is being mixed with proportional fonts. This happens a lot in technical documentation, for example. In such cases, you normally want the main font and the monospace font to have roughly similar x-heights, otherwise the lines end up with ugly bumps in them. But if the monospace font has a low x-height for its pitch, this means it looks uncomfortably stretched when set against the proportional font.

![mixed fonts](https://cloud.githubusercontent.com/assets/1890395/15746694/84c08bea-28cf-11e6-9aa1-9c00f179c37e.png)

In the image above, the pairs are

1. Source Sans Pro / Source Code Pro
2. DejaVu Sans / DejaVu Sans Mono
3. Calibri / Consolas
4. Droid Sans / Droid Mono

I think this works best when the medium-width letters (a, e, o, etc.) have about the same aspect ratio in both fonts: notably the case in lines 2 and 3 above. Line 1 does not look as harmonious to me.

**Comment by frankrolf** [comment]
This argument could go both ways. Of course your point is valid, SCP stands out in this case because of its wider proportions in comparison to SSP. But is that a bad thing?
Would it be beneficial to the reader to unify the appearance of the two typefaces, or would it be confusing? After all, proportional and monospaced fonts are supposed to convey two different things in the sentence.

Most implementations of code-within-text I’ve seen make an even `clearer distinction`, so the clear distinction could even be considered as a forte of SCP.

**Comment by alex-ball** [comment]
Well, two points on that. I used sans serif fonts in the example for a greater selection of comparators but in a printed context you would probably be mixing the (sans serif) monospace font with a proportional *serif* font, which usually gives sufficient contrast.

The other is that in a printed context you are more likely to be using full justification. Again, in code documentation you generally want to avoid hyphenating your quoted code words, and with a wider monospace font there are more chances of bad line breaks.

Just to be absolutely clear, I don't think anyone on this thread is saying SCP itself should be narrower. We're just registering the fact that there are cases where we would appreciate the option of a condensed variant.

**Comment by jimbo1qaz** [comment]
Check out https://github.com/nathco/Office-Code-Pro.

**Comment by dimitrieh** [comment]
@jimbo1qaz why that font, it isn't more condensed is it?

Anyway, I would like to opt for a condensed version of Source Code Pro for this issue https://github.com/zeit/hyper/issues/1331

> a condensed font family setting for smaller viewports/shells

**Comment by jimbo1qaz** [comment]
It looks taller than Source Code Pro at the same font size, which works much like condensing.

Sadly, it's missing lots of Unicode characters.

**Comment by alaadahmed** [comment]
@jimbo1qaz  which Unicode characters you mean? I meant by my question is this important for someone just use the font in terminal or in writing code in any editors? I tried the font you mentioned and I REALLY like it so much over Source Code Pro specially characters like ( 0, g, $, {} ) and I tried a lot of other characters and I found it just miss character like (Ω) which I don't think I will need to type ..

**Comment by curran** [comment]
Does anyone know how one might go about creating a derivative of Ubuntu Mono that uses 60% of the Em, rather than 50%?
