### ISSUE TITLE
How to reverse asterisk alignment

### ISSUE THREAD

**Issue by Shadowigor** [adobe-fonts/source-code-pro#157]
Hi

As discussed in #13, the asterisk is aligned with the + sign. As a C++ developer who mainly uses the asterisk for pointers I find this very confusing as it is very different to the fonts I'm used to. You mentioned [fontsquirrel.com](http://www.fontsquirrel.com/fontface/generator), but I could't really figure out how I could do it there. Any suggestions on how I could easily reverse that and get the old alignment back? I really like the font otherwise and would not like to switch.

**Comment by pauldhunt** [comment]
Miguel gives an alternate solution in #156, using [pyftfeatfreeze](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze). Let me know if this is a suitable workaround for your needs.

**Comment by zePanzerfaust** [comment]
@Shadowigor did you already make this change? I alreay made some changes to the font to fit my needs, including the asterisk. So it would not be a problem to realign it and create a version of the font, if you only need the asterisk changed. I would be willing to create Regular, Italic, Bold, Bold-Italic for you if you still have interest. These variants should be sufficient for most IDE's and their syntax highlighting.

**Comment by zePanzerfaust** [comment]
Just in case someone is interested in the instructions.

These instructions are ment for TTF's. Not sure if they work for OTF, but they should.

Prerequisite:
Adobe FDK
http://www.adobe.com/devnet/opentype/afdko/eula.html
(Get latest version for your platform. (atm. "AFDKO version 2.5 build 65781 April 3 2017"))

Download latest version of Source Code Pro
https://github.com/adobe-fonts/source-code-pro/releases


Now in case of the asterisk you are lucky, because the character (asterisk aligned with the top) is still part of the font.
You can check this with for example font forge and scrolling down to the end where some extra characters are stored.

On every font you want your asterisk changed repeat the following steps:
(ttx is part of the Adobe FDK)
1) ttx -t cmap SourceCodePro-XXX.ttf (XXX stands for the variation like Regular, Medium, etc.)
	(this prints the character map of the font)
2) Open the generated SourceCodePro-XXX.ttx (notice the ending .ttx)
3) Search for all <map code="0xSomeHex" name="asterisk"/> (important thing is 'name="asterisk"')
4) Replace all occurences with <map code="0xSomeHex" name="asterisk.a"/> (important thing is new name "asterisk.a")
5) Save the .ttx you just edited
6) ttx -o SourceCodePro-XXX.ttf -m SourceCodePro-XXX.ttf SourceCodePro-XXX.ttx
	(merge changes on SourceCodePro-XXX.ttx with SourceCodePro-XXX.ttf)

The resulting SourceCodePro-XXX.ttf has now the asterisk aligned with the top.

If you want to be compliant with the license, you might have to change the name of the font as we just modified the font?. And 'Source' is the Reserved Font Name.
This can be achieved in a similar fashion, instead of cmap just insert name. (https://github.com/adobe-fonts/source-code-pro/issues/65)

**Comment by Shadowigor** [comment]
Thank you! I forgot a bit about this issue to be honest, but I tried your suggestion and it works like a charm. I made a repo ([here](https://github.com/Shadowigor/font-asterisk-top)) with the updated font if someone is interested. I tried to replace all occurrences of 'Source' to comply with the licence, I hope there are none left.
