### ISSUE TITLE
Instructions how to get the latest zip

### ISSUE THREAD

**Issue by davidhedlund** [adobe-fonts/source-code-pro#196]
Most bash scripts used to get SCP with wget (yes I know that git can be used) are using this URL but it depends on a version number, I don't like that:

> wget https://github.com/adobe-fonts/source-code-pro/archive/2.010R-ro/1.030R-it.zip

How do I get the zip file for the files in https://github.com/adobe-fonts/source-code-pro/tree/release ?

Can you please document that in README.md?

**Comment by rpsrosario** [comment]
For future reference, since I've been looking the past few days at automating the installation of several different components in my system, you can use the [GitHub API](https://developer.github.com/v3/) to access the archive specified, e.g:
```sh
wget https://api.github.com/repos/adobe-fonts/source-code-pro/zipball/release --output-document source-code-pro.zip
```
---
On a side note you can even be fancier if you have [HTTPie](https://httpie.org/) and [jq](https://stedolan.github.io/jq/) installed in your system. With these tools (or similars) you can query the GitHub API specifically for the assets associated with the latest release of the repository. Something along the lines of:
```bash
assets_url=$(http --body GET \
  https://api.github.com/repos/adobe-fonts/source-code-pro/releases/latest \
  | jq --raw-output '.assets_url')

http --body GET "$assets_url" \
  | jq 'reduce .[] as $i ([]; . += [{"url": $i.browser_download_url, "name": $i.name}])')
```

Executing the above as of this comment yields:
```json
[
  {
    "url": "https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Italic.otf",
    "name": "SourceCodeVariable-Italic.otf"
  },
  {
    "url": "https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Italic.ttf",
    "name": "SourceCodeVariable-Italic.ttf"
  },
  {
    "url": "https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.otf",
    "name": "SourceCodeVariable-Roman.otf"
  },
  {
    "url": "https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.ttf",
    "name": "SourceCodeVariable-Roman.ttf"
  }
]
```

Which could be further processed for automatic download, installation and whatnot.
