### ISSUE TITLE
Bold font not aligning correctly.

### ISSUE THREAD

**Issue by platerza** [adobe-fonts/source-code-pro#203]
The bold font seems to be shifted upwards. I have no clue as to what could be the source of this issue.

Here is a screenshot to demonstrate.
![font-glitch-example](https://user-images.githubusercontent.com/20757930/44827458-3467a880-abe1-11e8-91a3-48907338952d.png)

And one more for good measure.
![2018-08-29-231821_1920x1080_scrot](https://user-images.githubusercontent.com/20757930/44827624-e010f880-abe1-11e8-8164-f1753745b356.png)

I was able to reproduce this under Void Linux and Gentoo Linux, under various terminal emulators: `st`, `xfce4-terminal`, `sakura`, `deepin-terminal`.

I am using `SourceCodePro` version 1.010.

**Comment by miguelsousa** [comment]
@platerza version 1.010 are variable fonts, a new format that is not expected to be supported in many places yet. Try installing the [latest non-variable fonts](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it) instead.

**Comment by platerza** [comment]
@miguelsousa Gotcha. Thanks for the info. By the way: under Arch Linux, the latest variable fonts seem to work flawlessly out of the box (also tested under the `st` terminal emulator). This might give a clue as to where the issue begins. Do you have any ideas as to what could be the cause?

**Comment by miguelsousa** [comment]
@platerza you must be using the variable TTFs, right?

**Comment by platerza** [comment]
@miguelsousa Under Arch, variable TTF's and OTF's seem to work.

**Comment by miguelsousa** [comment]
@platerza how exactly are you specifying the Bold style in those environments then?

**Comment by miguelsousa** [comment]
@platerza OK, thanks. I don't know why the Bold is not rendering on the same baseline as the other styles, but I'm almost certain it's not a font bug.

**Comment by platerza** [comment]
No problem. If you ever need testing on different configurations just give me a shout.

**Comment by platerza** [comment]
@miguelsousa on another note: I am putting together a package for SourceCodePro for the Void Linux repositories. Both `.otf` and `.ttf` versions are in the download. I tried both separately and did not see any functional difference. What is the best practice for distributing this font? Should one be preferred and installed, and while excluding the other? Or should both be installed? (Although this seems unnessecary to me... but what do I know? :nerd_face: )

**Comment by miguelsousa** [comment]
@platerza installing both is not a good idea, because that will quite likely create conflicts and odd behaviors.

In the past, from a user's POV, the decision between choosing OTFs or TTFs was mostly guided by the support (or lack thereof) for each of the formats, and by preferences on how each of them rendered on screen. These differences are largely gone nowadays, especially in the most recent versions of many software (and hardware, to some extent).

I'm biased to OTF(-CFF), since that's the format created by Adobe, and it's also the primary format in which the Source Code fonts are developed — the TTFs are made from the OTFs.

All things being equal, you could base your decision on the files' footprint.

**Comment by platerza** [comment]
@miguelsousa Thanks for the insight. It definitely cleared things up.

> ... it's also the primary format in which the Source Code fonts are developed — the TTFs are made from the OTFs.

Based on this, I think it might be best (from a package maintainer POV) to give preference to the format the font is developed in, rather than the 'converted' one. This seems like the cleanest solution.

**Comment by egmontkob** [comment]
See the upstream [VTE issue](https://gitlab.gnome.org/GNOME/vte/issues/137). (VTE is the terminal emulation widget behind `xfce4-terminal`, `sakura` and `deepin-terminal` out of the aforementioned terminals; but not behind `st`.)

Please let me know if you have any insight as for why Pango reports us different height and ascent values as the weight changes, e.g. whether the font contains this information or Pango does something silly.

**Comment by kenlunde** [comment]
@egmontkob My professional opinion, after inspecting the vertical metrics settings, is that Pango is doing something silly, and that _something silly_ likely involves using the font bounding box values that are specified in the _head_ table, which should not be used for line layout purposes. I confirmed that the actual vertical metrics settings, as specified in the _hhea_ and _OS/2_ tables, are harmonized across weights.

**Comment by egmontkob** [comment]
The underlying issue of varying height and ascent values across different weights is fixed in freetype-2.10.0, [this commit](https://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=a6feefdfefd6eb8e62728f40638241bb1d8c993e).

FreeType is used by both VTE (GTK, Pango), and the ST terminal, and I've verified that upgrading FreeType fixes the look of Source Code Pro in both.

---

It's unclear to me whether there's still something even further underlying issue in Source Code Pro and the affected fonts themselves; not necessarily a bug per se, just an inconsistency in how various weights are defined.

E.g. see a comment in the linked VTE bug: if I only install the Roman variable file then a certain set of weights are shifted compared to the rest. (I still get italic faces too, though; are they contained in the Roman file, and if so then what's the point of a separate Italic font?) If I install the Italic variable file too then the set of weights that are shifted (in case of the upright variant) becomes a totally different set. It's a mystery to me.
