### ISSUE TITLE
Different character ratio for size-13 (shorter & wider than 12 or 14)

### ISSUE THREAD

**Issue by ianpan870102** [adobe-fonts/source-code-pro#219]
When trying out Source Code Pro at size 12, 13, and 14, it seems to me that size 14 is a direct scale-up to size 12, but size 13 seems to be a little fatter than the usual proportion, any explanations why this happens?

**Comment by pauldhunt** [comment]
are you using the OTF or TTF versions of the fonts? Can you supply some screen shots for what you are describing?

**Comment by ianpan870102** [comment]
Hi @pauldhunt It seems like I completely missed the notification of your reply, my bad for replying this late. On further investigation, it appears that the difference in ratio only appears in the editor I was using (Emacs), it renders nicely in modern apps like Visual Studio Code, so I believe I should file a bug over at Emacs instead.
I'll close this issue now.

**Comment by frankrolf** [comment]
This has to do with the rasterization. The compromise made between pixel grid and actual outline is less ideal at 13 point, and may result in slightly different proportions (and this wouldn’t be a problem of Source Sans only).
Emacs probably is using a different rasterization method than VS Code, hence the visual difference.

**Comment by ianpan870102** [comment]
Thanks for the reply @frankrolf . This makes a lot of sense.

> less ideal at 13 point

So in general, can one say that using even number font sizes is more ideal? Or just the specific size 13 has a problem?

**Comment by frankrolf** [comment]
No, it’s not possible to generalize this way. Every font is different, and the sizes and relationships within fonts differ wildly. That said, a larger point size (or a 4K display) will always result in fewer proportional deviations, because this means that there simply are more pixels available.

There are fonts specifically drawn to preform best at a particular rasterization size, this one for 13pt, for example: https://github.com/TiroTypeworks/Slabo

**Comment by ianpan870102** [comment]
I see, thanks for the insight!
