### ISSUE TITLE
这款字体小写字母 i 可以去掉向左出头的设计吗？换成consolas字体的i

### ISSUE THREAD

**Issue by zengchulin** [adobe-fonts/source-code-pro#249]

**Comment by RuixiZhang42** [comment]
Translation of the title (slightly modified): **Is it possible to provide an alternative design of the Latin small `i` that doesn’t have serif at the top-left of the stem? For example, like the `i` in Consolas.**

But the OP seemed to have made a mistake: The `i` in Consolas does have serif, both at the top-left and at the bottom. (中文：OP是不是搞错了，Consolas里的小写`i`左上、底部都有出头的衬线)

Source Code Pro provides the bottom-seriffed `i` through Stylistic Set&nbsp;4. (中文：想要Consolas那种`i`，即上下都出头，可以调用Source Code Pro的Stylistic Set&nbsp;4)

![scpss04](https://user-images.githubusercontent.com/39968857/92745055-0381e880-f350-11ea-8a77-388b2f25b74b.png)

**Comment by pauldhunt** [comment]
@zengchulin I do not think that we will produce an alternate font with your preferred glyph shapes as the default, but the sources are open and you can do this yourself. The only issue then is to ensure that the name of the final font is changed to something other than “Source”. Otherwise if your code editor supports OpenType stylistic sets, you can just set the display to use SS04.
