### ISSUE TITLE
SCP cannot be styled in various apps (e.g. Sublime Text, VSCode) on macOS 11 (Big Sur)

### ISSUE THREAD

**Issue by thekeith** [adobe-fonts/source-code-pro#250]
For some reason, Source Code Pro is now incompatible with some apps on Big Sur such as Sublime Text 3. Removing and reinstalling the font did not help. Also raising this to the Sublime HQ team too.

**Comment by frankrolf** [comment]
Hi @thekeith, would you mind providing some more detail here?
- what does “now incompatible” mean? The fonts no longer work after installing 10.15?
- “some apps” – which apps?
- have you tried OTF versions?
- are you using the latest static release? https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it
- are you perhaps accidentally using Variable Fonts, which may not yet be supported by Sublime Text?
- “Also raising this to the Sublime HQ team too” – where?

**Comment by UnderpantsGnome** [comment]
@frankrolf I don't know if they are referring to the same issue, but on Big Sur, using VS Code, the font doesn't render any color other than black, so syntax highlight no longer works, I just checked it with the latest release of the TTF fonts.

**Comment by balupton** [comment]
Issue is also reported on vscode https://github.com/microsoft/vscode/issues/100840 as well as electron https://bugs.chromium.org/p/chromium/issues/detail?id=1100502

**Comment by balupton** [comment]
Perhaps https://github.com/adobe-fonts/source-code-pro/issues/244 is the same issue, just detected earlier somewhere else.

**Comment by Soulike** [comment]
Same problem on Chrome 86
![image](https://user-images.githubusercontent.com/23612560/99027437-35116d00-25a8-11eb-8bdc-157fc0e7874f.png)
![image](https://user-images.githubusercontent.com/23612560/99027465-4490b600-25a8-11eb-8a38-ef9c77d6390d.png)

**Comment by monadbobo** [comment]
> Issue is also reported on vscode [microsoft/vscode#100840](https://github.com/microsoft/vscode/issues/100840) as well as chromium https://bugs.chromium.org/p/chromium/issues/detail?id=1100502
> 
> Hasklig also has the same issue.

I had the same problem.

**Comment by frankrolf** [comment]
#244 is not related, since this is just a CSS issue – I just tested the site (fixed yesterday) and it works fine.
However, I think it is the same problem as #217, where Firefox would have this problem even in OSs prior to Mojave.

Explanation: Source Code Pro contains an experimental SVG table with colored glyphs in them:
<img width="1750" alt="Screen Shot 2020-11-13 at 10 42 17" src="https://user-images.githubusercontent.com/2049645/99058068-f4602680-259c-11eb-9126-14364a7b9846.png">

Apparently, the presence of this table confuses environments into thinking “Hey – this font is already colored! I should not touch it.” Pre-macOS 11 this only happened in Firefox, now it does in more applications; I am unsure where the bug lies though (stock apps don’t seem to have a problem with coloring the font).
The root cause however is the presence of the SVG table.

----

To test this hypothesis, I made a small test in Sublime:

**Other font (Input Mono)**
<img width="2672" alt="Screen Shot 2020-11-13 at 10 24 35" src="https://user-images.githubusercontent.com/2049645/99058783-f2e32e00-259d-11eb-94b7-a3a1b5b18238.png">

**Source Code Pro (2.030)**
<img width="2672" alt="Screen Shot 2020-11-13 at 10 24 41" src="https://user-images.githubusercontent.com/2049645/99058685-d8a95000-259d-11eb-8eb3-99ddd100f852.png">

**Source Code Pro (SVG table removed)**
<img width="2672" alt="Screen Shot 2020-11-13 at 10 35 30" src="https://user-images.githubusercontent.com/2049645/99058820-fd9dc300-259d-11eb-8244-ea94b9a9d20b.png">

@pauldhunt is currently working on SCP and can decide whether keeping the SVG table is worth the tradeoff.

FWIW I did test with OTF files, the file format does not seem to matter much in this bug. I will update the issue title accordingly.

**Comment by zavan** [comment]
@frankrolf @pauldhunt now with the final version of Big Sur released this problem potentially affects many more people. Have you made a decision on keeping the table and breaking compatibility vs removing it?

Since it was described as a "experimental" feature (and the fact that it breaks compatibility with other stable software), in my view it shouldn't make into what end users receive. One option would be to make two separate releases, one with the table, another without, or a making a "canary" release channel with experimental features while keeping them out of the regular one, like Google Chrome does.

**Comment by pauldhunt** [comment]
I’m planning on getting a patch out ASAP that removes the SVG table in hopes that will remedy this behavior. If you’d like to test some beta fonts, please contact me. Thanks.

**Comment by wbond** [comment]
We are tracking this for Sublime Text at https://github.com/sublimehq/sublime_text/issues/3747. I've outlined what I believe to be the correct changes if you are using Core Text. I have not made the changes to our font rendering stack yet.

**Comment by pauldhunt** [comment]
I’ve pushed out a new build of the fonts with SVG table removed to remedy this bug. Please update your fonts and let me know if this resolves the issue for you. Thanks. 
📦 https://github.com/adobe-fonts/source-code-pro/releases/latest

**Comment by jakedahn** [comment]
For what it's worth, I can confirm that the latest release you linked above fixes VSCode! I had to restart VSCode after reinstalling the font, but everything seems to be working for me -- thank you! 🥳

**Comment by manngo** [comment]
I had the same problem with Atom and Firefox, which led me to conclude that it was the font and not the software.

Thanks @thekeith for reporting this, and @pauldhunt for fixing it.

**Comment by mattrose** [comment]
I maintain the source-code-pro package on Fedora Linux, and I'm just wondering whether this new release has any known impact on anything other than MacOS.  Just wondering if it's worth packaging for Linux.

**Comment by frankrolf** [comment]
@mattrose #217 (font color assignment in Firefox) might be worth testing for.

**Comment by mattrose** [comment]
I looked at #217 and it didn't seem to affect anything but Macs (the bug states that Windows is OK)

**Comment by thekeith** [comment]
> Hi @thekeith, would you mind providing some more detail here?
> 
> * what does “now incompatible” mean? The fonts no longer work after installing 10.15?
> * “some apps” – which apps?
> * have you tried OTF versions?
> * are you using the latest static release? https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it
> * are you perhaps accidentally using Variable Fonts, which may not yet be supported by Sublime Text?
> * “Also raising this to the Sublime HQ team too” – where?

Thanks for the reply and my bad on taking so long to

**Comment by thekeith** [comment]
Accidentally closed the bug when making a reply.

**Comment by thekeith** [comment]
@frankrolf more details:

> what does “now incompatible” mean? The fonts no longer work after installing 10.15?

As noted in other tickets, colors were not properly rendering in Sublime Text and other code editors

> “some apps” – which apps?

Sublime Text, Atom

> have you tried OTF versions?

I tried the Google Font version just now and that fixed the issue. No downloaded releases from GitHub worked.

> are you using the latest static release? https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it

Yes

> are you perhaps accidentally using Variable Fonts, which may not yet be supported by Sublime Text?

Nope

> “Also raising this to the Sublime HQ team too” – where?

I mean I also sent to the Sublime Text team to raise the issue in case it was related to the app.

Thanks all for the help on this.

**Comment by frankrolf** [comment]
@thekeith 
There has been a new release since you filed this issue. May I ask you to check out https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro%2F1.052R-it%2F1.012R-VAR ?
Thanks!

**Comment by ddarbyson** [comment]
I also see colour-syntax not working in Sublime Text 3 under Big Sur when `"font_face": "Source Code Pro"` is defined in settings. I didn't have issue in Catalina.

**Comment by pauldhunt** [comment]
@ddarbyson which version of the Source Code fonts are you using? This issue should have been resolved in the latest builds.

**Comment by ddarbyson** [comment]
@pauldhunt I installed Big Sur on Wednesday (April 28th, 2021). Here's the info

```
$ brew info font-source-code-pro
font-source-code-pro: latest
https://fonts.google.com/specimen/Source+Code+Pro
/usr/local/Caskroom/font-source-code-pro/latest (17 files, 11.2KB)
From: https://github.com/Homebrew/homebrew-cask-fonts/blob/HEAD/Casks/font-source-code-pro.rb
==> Name
Source Code Pro
==> Description
None
==> Artifacts
SourceCodePro-SemiBoldItalic.ttf (Font)
SourceCodePro-BlackItalic.ttf (Font)
SourceCodePro-Bold.ttf (Font)
SourceCodePro-BoldItalic.ttf (Font)
SourceCodePro-ExtraLight.ttf (Font)
SourceCodePro-ExtraLightItalic.ttf (Font)
SourceCodePro-Italic.ttf (Font)
SourceCodePro-Light.ttf (Font)
SourceCodePro-LightItalic.ttf (Font)
SourceCodePro-Medium.ttf (Font)
SourceCodePro-MediumItalic.ttf (Font)
SourceCodePro-Regular.ttf (Font)
SourceCodePro-SemiBold.ttf (Font)
SourceCodePro-Black.ttf (Font)
```

**Comment by pauldhunt** [comment]
@ddarbyson i can see the font version numbers on your colleague’s report, but not on yours. can you tell me what version of the fonts you are using?

**Comment by ddarbyson** [comment]
Hey @pauldhunt how do I find that? The output is from `brew info` and it shows "/usr/local/Caskroom/font-source-code-pro/latest" for my version.

**Comment by frankrolf** [comment]
I don’t know who maintains the brew install for Source Code Pro, but it seems it points to Google Fonts for the binaries:
https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-source-code-pro.rb

The version available on Google Fonts might not be the latest.
