### ISSUE TITLE
"Zero slash" from right to left, instead of left to right

### ISSUE THREAD

**Issue by resolritter** [adobe-fonts/source-code-pro#300]
Thank you for this font.

I was wondering if it would be possible to have a variant of the `ZERO_SLASH` feature (perhaps `ZERO_SLASH_RTL` or something along those lines) which has a slash from right to left, instead of the current left to right.

The motivation is: other fonts I'm used to, included, but not limited to

- Consolas
- Iosevka
- Fira Code
- Inconsolata

All have the zero slash go from right to left, so I'm more used to it being that way.

EDIT: I'm far from a font expert but those fonts might've been inspired by https://en.wikipedia.org/wiki/Terminal_(typeface).

![](https://upload.wikimedia.org/wikipedia/commons/c/c8/Font_Terminal_Sample.png)

**Comment by pauldhunt** [comment]
@resolritter Thanks for your feedback. The reversed slash is by design to prevent confusion with Ø and ø. Having the slash run the other way means that there is no ambiguity when these characters are found in proximity to each other. If you prefer the slash running the other way, please feel free to make a custom version according to your preference but be sure to change the name of the fonts to not use the name ‘Source’. Thanks and best of luck!

**Comment by resolritter** [comment]
Alright

**Comment by resolritter** [comment]
For anyone who might be interested in the future, the files which would be changed are `zero.0.glif`, `zero.0c.glif`, `zero.0o.glif`; specifically this part, which is the slash:

https://github.com/adobe-fonts/source-code-pro/blob/992a20b872091ca8d5823283df9d76624f8f4eb4/Roman/Masters/master_1/SourceCode_Regular.ufo/glyphs/zero.0.glif#L33-L38

The files are related to:

https://github.com/adobe-fonts/source-code-pro/blob/992a20b872091ca8d5823283df9d76624f8f4eb4/Roman/familyGSUB.fea#L351

After taking https://github.com/adobe-fonts/source-code-pro/issues/300#issuecomment-1253138812 into consideration I think it's a good idea to have the slash go from left to right, so I'm not interested in this proposal anymore.
