### ISSUE TITLE
Increase font height

### ISSUE THREAD

**Issue by chmielcode** [adobe-fonts/source-code-pro#318]
Hi, I've discovered Office Code Pro, which is based on a very old build of Source Code Pro and looks absolutely perfect in notepad++ (size 9) and vscode (size 12) while Source Code Pro is a little bit too small. Other fonts like JetBrains Mono, Cascadia Mono, Noto Sans Mono etc. look good at this size, but I prefer Source Code Pro style. Would you please consider increasing the height of this font to match all other popular fonts or maybe suggest any way to do it myself? Author of Office Code Pro is inactive for years and I would love to have recent Source Code Pro with similar size to Office Code Pro.

Thank you very much for your work :)

**Comment by pauldhunt** [comment]
I have actually begun some preliminary work adding a Variable Font (VF) axis that would allow the user to vary the x-height to their preference. There is no slated delivery day for this feature, however. I hope to get back on this project sometime later this year. There’s a lot I want to do with the next major release.

**Comment by chmielcode** [comment]
That's great news, thank you :)

**Comment by D0J0P** [comment]
Question: Is the default x-height of SourceCodeVF higher than regular Source Code Pro? And like chmielcode asked, how do you configure it to have a higher x-height like JetBrains Mono does?

**Comment by D0J0P** [comment]
Here is how these fonts look in font manager(GTK app). JetBrains Mono is on top, SCP in the middle, and GoMono on the bottom:
![2024-04-05-000957_1920x1080_scrot](https://github.com/adobe-fonts/source-code-pro/assets/19495660/25665509-00d5-4c12-a6a8-3a0ff4a0ec99)

JB Mono looks tall, but so does GoMono, and it has some nice width to it like SCP. Could SCP be made to have the same x-height as them instead of setting it in the variable version? 

A good article by Go: [https://go.dev/blog/go-fonts](url)
